### ISSUE TITLE
TypeError: forward() takes from 3 to 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by ltbupt** [yanglan0225/s3net#2]
Traceback (most recent call last):
  File "train.py", line 101, in <module>
    output, prediction, link_loss, ent_loss = model(inputs)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/SketchCls/s3net-master/src/model.py", line 116, in forward
    s = self.gnn1_pool(x, adj)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/SketchCls/s3net-master/src/model.py", line 48, in forward
    x1 = self.bn(1, F.relu(self.conv1(x0, adj, mask, self.add_loop)))
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() takes from 3 to 4 positional arguments but 5 were given
I met this problem when I tried to train a  s3net model,can u give me some help?

**Comment by yanglan0225** [comment]
please check the version of your PyG package.
